### ISSUE TITLE
Not Compatible with PyInstaller

### ISSUE THREAD

**Issue by asdat3** [synchronizing/mitm#30]
locally the .exe works fine, on other system its just returning this:

```
Traceback (most recent call last):
  File "pbr\version.py", line 451, in _get_version_from_pkg_resources
  File "pkg_resources__init.py", line 342, in get_provider
  File "pkg_resources__init.py", line 886, in require
  File "pkg_resources__init.py", line 772, in resolve
pkg_resources.DistributionNotFound: The 'mitm' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<dist\obf\main.py>", line 3, in <module>
  File "<frozen main>", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "mitm__init.py", line 15, in <module>
  File "pbr\version.py", line 485, in release_string
  File "pbr\version.py", line 495, in semantic_version
  File "pbr\version.py", line 458, in _get_version_from_pkg_resources
  File "pbr\packaging.py", line 872, in get_version
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mitm was given, but was not able to be found.
[12828] Failed to execute script 'main' due to unhandled exception!
```

command used to create .exe:
`pyarmor-7 pack -e " --onefile --icon main_free.ico" main.py`

**Comment by synchronizing** [comment]
That error is due to `pbr`. An easy fix is using the following env var: 
```
PBR_VERSION=1.4.2
```
to set `mitm` versioning during install.

**Comment by synchronizing** [comment]
Closing this issue for now. Feel free to reply if any other information is needed.
